<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 trả lời',
		'1_comment' => '1 bình luận',
		'1_day' => '1 ngày',
		'1_disliked' => '1 không thích',
		'1_flag' => '1 flag',
		'1_hour' => '1 giờ',
		'1_liked' => '1 thích',
		'1_minute' => '1 phút',
		'1_month' => '1 tháng',
		'1_point' => '1 điểm',
		'1_question' => '1 câu hỏi',
		'1_second' => '1 giây',
		'1_tag' => '1 từ khóa',
		'1_user' => '1 người dùng',
		'1_view' => '1 xem',
		'1_vote' => '1 vote',
		'1_week' => '1 tuần',
		'1_year' => '1 năm',
		'add_category_x_favorites' => 'Thêm  ^ vào thể loại yêu thích của tôi ',
		'add_favorites' => 'Thêm vào yêu thích',
		'add_tag_x_favorites' => 'Thêm ^ vào yêu thích của tôi',
		'all_categories' => 'Tất cả thể loại',
		'anonymous' => 'vô danh',
		'answer_edited' => 'answer edited',
		'answer_reshown' => 'answer reshown',
		'answer_selected' => 'answer selected',
		'answered' => 'trả lời',
		'answered_qs_in_x' => 'Câu hỏi được trả lời nhiều nhất trong ^',
		'answered_qs_title' => 'Câu hỏi được trả lời nhiều nhất',
		'asked' => 'đã hỏi',
		'asked_related_q' => 'asked related question',
		'by_x' => 'bởi^',
		'cancel_button' => 'Bỏ qua',
		'closed' => 'đã đóng',
		'comment_edited' => 'comment edited',
		'comment_moved' => 'comment moved',
		'comment_reshown' => 'comment reshown',
		'commented' => 'commented',
		'date_day_min_digits' => 1, // 1 or 2
		'date_format_other_years' => '^month ^day, ^year',
		'date_format_this_year' => '^month ^day',
		'date_month_1' => 'Jan',
		'date_month_2' => 'Feb',
		'date_month_3' => 'Mar',
		'date_month_4' => 'Apr',
		'date_month_5' => 'May',
		'date_month_6' => 'Jun',
		'date_month_7' => 'Jul',
		'date_month_8' => 'Aug',
		'date_month_9' => 'Sep',
		'date_month_10' => 'Oct',
		'date_month_11' => 'Nov',
		'date_month_12' => 'Dec',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'đã sửa',
		'email_error' => 'An error occurred trying to send the email.',
		'field_required' => 'Please enter something in this field',
		'file_upload_limit_exceeded' => 'The size of the file exceeds the server\'s limits',
		'general_error' => 'A server error occurred - please try again.',
		'hidden' => 'hidden',
		'highest_users' => 'Top scoring users',
		'hot_qs_in_x' => 'Hot questions in ^',
		'hot_qs_title' => 'Hot questions',
		'image_not_read' => 'The image could not be read. Please upload one of: ^',
		'image_too_big_x_pc' => 'This image is too big. Please scale to ^% then try again.',
		'in_category_x' => 'trong ^',
		'ip_address_x' => 'địa chỉ IP  ^',
		'logged_in_x' => 'Xin chào ^',
		'max_length_x' => 'Maximum length is ^ characters',
		'max_upload_size_x' => 'Maximum upload size is ^',
		'me' => 'tôi',
		'meta_order' => '^what^when^where^who', // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Please provide more information - at least ^ characters',
		'moved' => 'moved',
		'nav_activity' => 'Tất cả hoạt động',
		'nav_admin' => 'Admin',
		'nav_ask' => 'Tạo một câu hỏi',
		'nav_categories' => 'Thể loại',
		'nav_feedback' => 'Gửi phản hồi',
		'nav_home' => 'Trang chủ',
		'nav_hot' => 'Mới!',
		'nav_login' => 'Đăng nhập',
		'nav_logout' => 'Thoát',
		'nav_most_answers' => 'Most answers',
		'nav_most_recent' => 'Gần đây',
		'nav_most_views' => 'Xem nhiều nhất',
		'nav_most_votes' => 'Thích nhiều nhất',
		'nav_no_answer' => 'Không có câu trả lời',
		'nav_no_selected_answer' => 'Chưa chấp nhận',
		'nav_no_upvoted_answer' => 'Chưa ai thích',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Câu hỏi',
		'nav_register' => 'Đăng ký',
		'nav_tags' => 'Từ khóa',
		'nav_unanswered' => 'Chưa trả có câu trả lời',
		'nav_updates' => 'Cập nhật của tôi',
		'nav_users' => 'Người dùng',
		'no_active_users' => 'No active users found',
		'no_answers_found' => 'No answers found',
		'no_answers_in_x' => 'No answers in ^',
		'no_categories_found' => 'No categories found',
		'no_category' => 'No category',
		'no_comments_found' => 'No comments found',
		'no_comments_in_x' => 'No comments in ^',
		'no_questions_found' => 'No questions found',
		'no_questions_in_x' => 'No questions in ^',
		'no_related_qs_title' => 'No related questions found',
		'no_results_for_x' => 'No results found for ^',
		'no_tags_found' => 'No tags found',
		'no_una_questions_found' => 'No unanswered questions found',
		'no_una_questions_in_x' => 'No unanswered questions in ^',
		'no_unselected_qs_found' => 'No questions found without a selected answer',
		'no_unupvoteda_qs_found' => 'No questions found without an upvoted answer',
		'page_label' => 'Trang:',
		'page_next' => 'next',
		'page_not_found' => 'Không tìm thấy trang',
		'page_prev' => 'prev',
		'popular_tags' => 'Từ khóa phổ biến nhất',
		'questions_tagged_x' => 'Recent questions tagged ^',
		'recategorized' => 'recategorized',
		'recent_activity_in_x' => 'Recent activity in ^',
		'recent_activity_title' => 'Hoạt động gần đây',
		'recent_as_in_x' => 'Recently answered questions in ^',
		'recent_as_title' => 'Recently answered questions',
		'recent_cs_in_x' => 'Recently commented questions in ^',
		'recent_cs_title' => 'Recently commented questions',
		'recent_qs_as_in_x' => 'Recent questions and answers in ^',
		'recent_qs_as_title' => 'Recent questions and answers',
		'recent_qs_in_x' => 'Recent questions in ^',
		'recent_qs_title' => 'Những câu hỏi gần đây',
		'related_qs_title' => 'Những câu hỏi liên quan',
		'remove_favorites' => 'Remove from my favorites',
		'remove_x_favorites' => 'Remove ^ from my favorites',
		'reopened' => 'reopened',
		'reshown' => 'reshown',
		'results_for_x' => 'Kết quả tìm kiếm cho ^',
		'retagged' => 'retagged',
		'save_button' => 'Lưu thay đổi',
		'search_button' => 'Tìm kiếm',
		'search_explanation' => 'Hãy đánh từ khóa tìm kiếm vào ô nhập một lần nữa.',
		'search_title' => 'Kết quả tìm kiếm',
		'selected' => 'đã chọn',
		'send_button' => 'Gửi',
		'since_x' => 'từ ^',
		'suggest_ask' => 'Hãy bắt đầu mọi thứ ^1bằng một câu hỏi^2.',
		'suggest_category_qs' => 'To see more, click for all the ^1questions in this category^2.',
		'suggest_qs' => 'To see more, click for the ^1full list of questions^2.',
		'suggest_qs_tags' => 'To see more, click for the ^1full list of questions^2 or ^3popular tags^4.',
		'to_x' => 'to ^',
		'unanswered_qs_in_x' => 'Questions without answers in ^',
		'unanswered_qs_title' => 'Những câu hỏi chưa có câu trả lời',
		'unselected_qs_in_x' => 'Questions without a selected answer in ^',
		'unselected_qs_title' => 'Những câu hỏi có câu trả lời nhưng chưa được chấp nhận',
		'unupvoteda_qs_in_x' => 'Questions without an upvoted answer in ^',
		'unupvoteda_qs_title' => 'Recent questions without an upvoted answer',
		'upload_limit' => 'Too many uploads - please try again in an hour',
		'view_q_must_be_approved' => 'Your account must be approved to view question pages.',
		'view_q_must_confirm' => 'Please ^5confirm your email address^6 to view question pages.',
		'view_q_must_login' => 'Please ^1log in^2 or ^3register^4 to view question pages.',
		'viewed_qs_in_x' => 'Câu hỏi được xem nhiều nhất trong ^',
		'viewed_qs_title' => 'Câu hỏi được xem nhiều nhất',
		'vote_disabled_approve' => 'You account must be approved before you can vote',
		'vote_disabled_down' => 'Voting down is only available to some users',
		'vote_disabled_down_approve' => 'Your account must be approved before you can vote down',
		'vote_disabled_hidden_a' => 'You cannot vote on hidden answers',
		'vote_disabled_hidden_q' => 'You cannot vote on hidden questions',
		'vote_disabled_level' => 'Voting is only available to some users',
		'vote_disabled_my_a' => 'You cannot vote on your own answers',
		'vote_disabled_my_q' => 'You cannot vote on your own questions',
		'vote_disabled_q_page_only' => 'Please view this question to vote',
		'vote_down_must_confirm' => 'Please ^5confirm your email address^6 to vote down.',
		'vote_down_popup' => 'Click to vote down',
		'vote_limit' => 'Too many votes received - please try again in an hour',
		'vote_must_confirm' => 'Please ^5confirm your email address^6 to vote.',
		'vote_must_login' => 'Please ^1log in^2 or ^3register^4 to vote.',
		'vote_not_allowed' => 'Voting on this is not allowed',
		'vote_up_popup' => 'Click to vote up',
		'voted_down_popup' => 'You have voted this down - click to remove vote',
		'voted_qs_in_x' => 'Highest voted questions in ^',
		'voted_qs_title' => 'Highest voted questions',
		'voted_up_popup' => 'You have voted this up - click to remove vote',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ trước',
		'x_answers' => '^ trả lời',
		'x_comments' => '^ bình luận',
		'x_days' => '^ ngày',
		'x_disliked' => '^ k thích',
		'x_flags' => '^ flags',
		'x_hours' => '^ giờ',
		'x_liked' => '^ thích',
		'x_minutes' => '^ minutes',
		'x_months' => '^ tháng',
		'x_points' => '^ điểm',
		'x_questions' => '^ câu hỏi',
		'x_seconds' => '^ giây',
		'x_tags' => '^ từ khóa',
		'x_users' => '^ người',
		'x_views' => '^ xem',
		'x_votes' => '^ votes',
		'x_weeks' => '^ tuần',
		'x_years' => '^ năm',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/