<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Câu trả lời',
		'a_convert_to_c' => 'Chuyển câu trả lời này thành bình luận',
		'a_convert_to_c_on' => 'Chuyển câu trả lời này thành bình luận cho:',
		'a_convert_warn' => 'Warning: This conversion cannot be reversed.',
		'a_convert_warn_cs' => 'Warning: This conversion cannot be reversed and will also move this answer\'s comments.',
		'a_notify_email' => 'Gửi email cho tôi vào địa chỉ này nếu câu trả lời được chấp nhận hoặc có bình luận:',
		'a_notify_label' => 'Gửi email cho tôi nếu câu trả lời được chấp nhận hoặc có bình luận',
		'a_notify_x_label' => 'Gửi email cho tôi (^) nếu câu trả lời được chấp nhận hoặc có bình luận',
		'a_waiting_your_approval' => 'This answer is waiting for your approval',
		'a_your_waiting_approval' => 'Your answer will be checked and approved shortly.',
		'add_answer_button' => 'Thêm trả lời',
		'add_comment_button' => 'Thêm bình luận',
		'add_q_favorites' => 'Thêm câu hỏi này vào yêu thích',
		'anon_name_label' => 'Tên hiển thị của bạn (tùy chọn):',
		'answer_button' => 'trả lời',
		'answer_limit' => 'Quá nhiều câu trả lời  vào lúc này - hãy thử lại trong 1 giờ',
		'answer_must_be_approved' => 'Your account must be approved before you answer a question.',
		'answer_must_confirm' => 'Please ^5confirm your email address^6 to answer this question.',
		'answer_must_login' => 'Please ^1log in^2 or ^3register^4 to answer this question.',
		'answer_q_popup' => 'Trả lời câu hỏi này',
		'approve_a_popup' => 'Chấp nhận câu trả lời này',
		'approve_button' => 'chấp nhận',
		'approve_c_popup' => 'Chấp nhận bình luận này',
		'approve_q_popup' => 'Chấp nhận câu hỏi này',
		'ask_button' => 'Tạo câu hỏi',
		'ask_follow_from_a' => 'Câu hỏi của bạn sẽ liên quan đến câu trả lời này:',
		'ask_follow_title' => 'Tạo câu hỏi liên quan',
		'ask_limit' => 'Too many questions received - please try again in an hour',
		'ask_must_be_approved' => 'Your account must be approved before you ask a question.',
		'ask_must_confirm' => 'Please ^5confirm your email address^6 to ask a question.',
		'ask_must_login' => 'Please ^1log in^2 or ^3register^4 to ask a question.',
		'ask_same_q' => 'Before proceeding, please check your question was not asked already:',
		'ask_title' => 'Tạo câu hỏi',
		'c_notify_email' => 'Email me at this address if a comment is added after mine:',
		'c_notify_label' => 'Email me if a comment is added after mine',
		'c_notify_x_label' => 'Email me (^) if a comment is added after mine',
		'c_waiting_your_approval' => 'This comment is waiting for your approval',
		'c_your_waiting_approval' => 'Your comment will be checked and approved shortly.',
		'category_ask_not_allowed' => 'You do not have permission to ask questions in this category',
		'category_js_note' => 'To select any category, please enable Javascript in your web browser.',
		'category_required' => 'Hãy chọn thể loại',
		'claim_a_popup' => 'Gán câu trả lời này cho tài khoản của bạn',
		'claim_button' => 'Tôi đã viết',
		'claim_c_popup' => 'Assign this comment to your user account',
		'claim_q_popup' => 'Assign this question to your user account',
		'clear_flags_button' => 'clear flags',
		'clear_flags_popup' => 'Remove flags by all users',
		'close_button' => 'đóng',
		'close_duplicate' => 'Câu hỏi này bị trùng với câu hỏi khác',
		'close_duplicate_error' => 'The duplicate question could not be found - please try entering the number from a different question URL, e.g. 123.',
		'close_form_button' => 'Đóng câu hỏi',
		'close_form_title' => 'Đóng câu hỏi này',
		'close_original_note' => 'You can also enter the question number from the URL, e.g. 123.',
		'close_original_title' => 'URL of the original question:',
		'close_q_popup' => 'Close this question to any new answers',
		'close_reason_title' => 'Reason for closing this question:',
		'closed_as_duplicate' => 'closed as a duplicate of:',
		'closed_with_note' => 'closed with the note:',
		'comment_a_popup' => 'Add a comment on this answer',
		'comment_button' => 'bình luận',
		'comment_limit' => 'Too many comments received - please try again in an hour',
		'comment_must_be_approved' => 'Your account must be approved before you add a comment.',
		'comment_must_confirm' => 'Please ^5confirm your email address^6 to add a comment.',
		'comment_must_login' => 'Please ^1log in^2 or ^3register^4 to add a comment.',
		'comment_on_a' => 'Trong trả lời: ',
		'comment_on_q' => 'Trong câu hỏi: ',
		'comment_q_popup' => 'Thêm bình luận cho câu hỏi này',
		'delete_a_popup' => 'Xóa câu trả lời này vĩnh viễn',
		'delete_button' => 'xóa',
		'delete_c_popup' => 'Xóa bình luận này vĩnh viễn',
		'delete_q_popup' => 'Xóa câu hỏi này vĩnh viễn',
		'duplicate_content' => 'Your submission appears to be a duplicate.',
		'edit_a_popup' => 'Sửa câu trả lời',
		'edit_a_title' => 'Sửa câu trả lời',
		'edit_button' => 'sửa',
		'edit_c_popup' => 'Sửa bình luận này',
		'edit_c_title' => 'Sửa bình luận',
		'edit_must_confirm' => 'Please ^5confirm your email address^6 to edit this.',
		'edit_must_login' => 'Please ^1log in^2 or ^3register^4 to edit this.',
		'edit_q_popup' => 'Sửa câu hỏi này',
		'edit_q_title' => 'Sửa câu hỏi',
		'example_tags' => 'Ví dụ từ khóa: ',
		'flag_a_popup' => 'Flag this answer as spam or inappropriate',
		'flag_button' => 'flag',
		'flag_c_popup' => 'Flag this comment as spam or inappropriate',
		'flag_hide_button' => 'flag and hide',
		'flag_limit' => 'Too many posts flagged - please try again in an hour',
		'flag_must_confirm' => 'Please ^5confirm your email address^6 to flag posts.',
		'flag_must_login' => 'Please ^1log in^2 or ^3register^4 to flag posts.',
		'flag_not_allowed' => 'Flagging this is not allowed',
		'flag_q_popup' => 'Flag this question as spam or inappropriate',
		'follow_a_popup' => 'Tạo câu hỏi liên quan đến câu trả lời này',
		'follow_button' => 'tạo câu hỏi liên quan',
		'follows_a' => 'related to an answer for:',
		'follows_q' => 'thông tin về câu hỏi:',
		'hide_a_popup' => 'Ẩn câu trả lời này',
		'hide_button' => 'ẩn',
		'hide_c_popup' => 'Ẩn bình luận này',
		'hide_q_popup' => 'Ẩn câu hỏi này',
		'matching_tags' => 'Matching tags: ',
		'max_tags_x' => 'A maximum of ^ tags are allowed',
		'min_tags_x' => 'Please provide at least ^ tag/s',
		'notify_email_note' => 'Privacy: Your email address will only be used for sending these notifications.',
		'q_category_label' => 'Thể loại:',
		'q_content_label' => 'Thông tin về câu hỏi:',
		'q_hidden_author' => 'Câu hỏi này đã bị ẩn bởi người tạo',
		'q_hidden_flagged' => 'This question has been flagged and hidden',
		'q_hidden_other' => 'Câu hỏi này đã bị ẩn',
		'q_notify_email' => 'Gửi email cho tôi vào địa chỉ này nếu câu trả lời được chấp nhận hoặc có bình luận:',
		'q_notify_label' => 'Gửi email cho tôi nếu câu trả lời được chấp nhận hoặc có bình luận',
		'q_notify_x_label' => 'Gửi email cho tôi (^) nếu câu trả lời được chấp nhận hoặc có bình luận',
		'q_tags_comma_label' => 'Tags - use comma (,) as a separator:',
		'q_tags_label' => 'Từ khóa - dùng dấu "-" để nối các từ:',
		'q_title_label' => 'Câu hỏi trong một dòng:',
		'q_waiting_approval' => 'This question is waiting for approval',
		'q_waiting_your_approval' => 'This question is waiting for your approval',
		'q_your_waiting_approval' => 'Your question will be checked and approved shortly.',
		'recat_button' => 'recategorize',
		'recat_popup' => 'Change this question\'s category',
		'recat_q_title' => 'Recategorize question',
		'reject_a_popup' => 'Từ chối trả lời này',
		'reject_button' => 'từ chối',
		'reject_c_popup' => 'Từ chối bình luận này',
		'reject_q_popup' => 'Từ chối câu hỏi này',
		'remove_q_favorites' => 'Remove this question from my favorites',
		'reopen_button' => 'mở lại',
		'reopen_q_popup' => 'Mở lại câu hỏi này',
		'reply_button' => 'trả lời',
		'reply_c_popup' => 'Hiện lại bình luận',
		'reshow_a_popup' => 'Hiện lại câu hỏi',
		'reshow_button' => 'hiện lại',
		'reshow_c_popup' => 'Hiện lại bình luận này',
		'reshow_q_popup' => 'Hiện lại câu hỏi này',
		'retag_button' => 'retag',
		'retag_cat_popup' => 'Change this question\'s category or tags',
		'retag_popup' => 'Change this question\'s tags',
		'retag_q_title' => 'Retag question',
		'save_silent_label' => 'Save silently to hide that this was edited',
		'select_popup' => 'Click to select as best answer',
		'select_text' => 'Câu trả lời hay nhất',
		'show_1_comment' => 'Hiển thị một bình luận',
		'show_1_previous_comment' => 'Show 1 previous comment',
		'show_x_comments' => 'Hiển thị ^ bình luận',
		'show_x_previous_comments' => 'Show ^ previous comments',
		'unflag_button' => 'unflag',
		'unflag_popup' => 'Remove the flag that you added',
		'unselect_popup' => 'Click to remove selection',
		'x_answers_title' => '^ Trả lời',
		'your_answer_title' => 'Trả lời của bạn',
		'your_comment_a' => 'Bình luận của bạn cho câu hỏi này:',
		'your_comment_q' => 'Bình luận của bạn về câu hỏi này:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
