<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-question.php
	Description: Language phrases for question page


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer_title' => '1 Câu trả lời',
		'a_convert_to_c' => 'Chuyển câu trả lời này thành bình luận',
		'a_convert_to_c_on' => 'Chuyển câu trả lời này thành bình luận cho:',
		'a_convert_warn' => 'Chú ý: Không thể hoàn tác sau khi chuyển đổi.',
		'a_convert_warn_cs' => 'Chú ý: Không thể hoàn tác sau khi chuyển đổi và nó cũng chuyển luôn bình luận của câu hỏi.',
		'a_notify_email' => 'Gửi email cho tôi vào địa chỉ này nếu câu trả lời được chấp nhận hoặc có bình luận:',
		'a_notify_label' => 'Gửi email cho tôi nếu câu trả lời được chấp nhận hoặc có bình luận',
		'a_notify_x_label' => 'Gửi email cho tôi (^) nếu câu trả lời được chấp nhận hoặc có bình luận',
		'a_waiting_your_approval' => 'Câu trả lời này đang chờ để được chọn',
		'a_your_waiting_approval' => 'Câu trả lời của bạn sẽ được chọn và chấp nhận ngay thôi.',
		'add_answer_button' => 'Đăng câu trả lời',
		'add_comment_button' => 'Đăng bình luận',
		'add_q_favorites' => 'Thêm câu hỏi này vào yêu thích',
		'anon_name_label' => 'Tên hiển thị của bạn (tùy chọn):',
		'answer_button' => 'trả lời',
		'answer_limit' => 'Quá nhiều câu trả lời  vào lúc này - hãy thử lại trong 1 giờ',
		'answer_must_be_approved' => 'Tài khoản của bạn phải được xác nhận trước khi trả lời câu hỏi.',
		'answer_must_confirm' => 'Hãy ^5xác nhận địa chỉ email của bạn^6 để trả lời câu hỏi này.',
		'answer_must_login' => 'Hãy ^1đăng nhập^2 hoặc ^3đăng ký^4 để trả lời câu hỏi này.',
		'answer_q_popup' => 'Trả lời câu hỏi này',
		'approve_a_popup' => 'Chấp nhận câu trả lời này',
		'approve_button' => 'chấp nhận',
		'approve_c_popup' => 'Chấp nhận bình luận này',
		'approve_q_popup' => 'Chấp nhận câu hỏi này',
		'ask_button' => 'Đăng câu hỏi',
		'ask_follow_from_a' => 'Câu hỏi của bạn sẽ liên quan đến câu trả lời này:',
		'ask_follow_title' => 'Tạo câu hỏi liên quan',
		'ask_limit' => 'Máy chủ nhận được quá nhiều câu hỏi lúc này - hãy thử lại trong 1 giờ',
		'ask_must_be_approved' => 'Tài khoản của bạn phải được xác nhận trước khi tạo một câu hỏi.',
		'ask_must_confirm' => 'Hãy ^5xác nhận địa chỉ email của bạn^6 để tạo câu hỏi.',
		'ask_must_login' => 'Hãy ^1đăng nhập^2 hoặc ^3đăng ký^4 để tạo câu hỏi.',
		'ask_same_q' => 'Trước khi bắt đầu, hãy kiểm tra xem đã có ai hỏi giống bạn chưa:',
		'ask_title' => 'Tạo câu hỏi',
		'c_notify_email' => 'Gửi email cho tôi vào địa chỉ này nếu có người thêm bình luận sau tôi:',
		'c_notify_label' => 'Gửi email cho tôi vào địa chỉ này nếu có người thêm bình luận sau tôi',
		'c_notify_x_label' => 'Gửi email cho tôi (^) nếu có người thêm bình luận sau tôi',
		'c_waiting_your_approval' => 'Bình luận này đang chờ được bạn xác nhận',
		'c_your_waiting_approval' => 'Bình luận của bạn sẽ được chọn và xác nhận ngay thôi.',
		'category_ask_not_allowed' => 'Bạn không có quyền tạo câu hỏi trong danh mục này',
		'category_js_note' => 'Để chọn được thể loại, bãn hãy cho phép mã Javascript được phép thực thi trên trình duyệt.',
		'category_required' => 'Hãy chọn thể loại',
		'claim_a_popup' => 'Gán câu trả lời này cho tài khoản của bạn',
		'claim_button' => 'Tôi đã viết',
		'claim_c_popup' => 'Gán bình luận này cho người dùng',
		'claim_q_popup' => 'Gán câu hỏi này cho người dùng',
		'clear_flags_button' => 'xóa hết vi phạm',
		'clear_flags_popup' => 'Xóa hết vi phạm bởi người dùng',
		'close_button' => 'đóng',
		'close_duplicate' => 'Câu hỏi này bị trùng với câu hỏi khác',
		'close_duplicate_error' => 'Không thể tìm thấy câu hỏi bị trùng - hãy thử bằng cách nhập định danh của câu hỏi lên đường dẫn URL, ví dụ: 123.',
		'close_form_button' => 'Đóng câu hỏi',
		'close_form_title' => 'Đóng câu hỏi này',
		'close_original_note' => 'Bạn có thể đánh số thứ tự của câu hỏi lên đường dẫn URL, v.d: 123.',
		'close_original_title' => 'Đường dẫn URL của câu hỏi gốc:',
		'close_q_popup' => 'Đóng câu hỏi này - không nhận thêm câu trả lời',
		'close_reason_title' => 'Lý do để đóng câu hỏi này:',
		'closed_as_duplicate' => 'đã đóng vì bị trùng với:',
		'closed_with_note' => 'đã đóng lại với ghi chú:',
		'comment_a_popup' => 'Bình luận câu trả lời này',
		'comment_button' => 'bình luận',
		'comment_limit' => 'Có quá nhiều bình luận - hãy thử lại trong 1 giờ',
		'comment_must_be_approved' => 'Tài khoản của bạn phải được xác thực trước khi thêm một bình luận.',
		'comment_must_confirm' => 'Hãy ^5xác thực địa chỉ email của bạn^6 để thêm bình luận.',
		'comment_must_login' => 'Hãy ^1đăng nhập^2 hoặc ^3đăng ký^4 để thêm bình luận.',
		'comment_on_a' => 'Trong trả lời: ',
		'comment_on_q' => 'Trong câu hỏi: ',
		'comment_q_popup' => 'Bình luận câu hỏi này',
		'delete_a_popup' => 'Xóa câu trả lời này vĩnh viễn',
		'delete_button' => 'xóa',
		'delete_c_popup' => 'Xóa bình luận này vĩnh viễn',
		'delete_q_popup' => 'Xóa câu hỏi này vĩnh viễn',
		'duplicate_content' => 'Câu hỏi của bạn đã bị trùng với một câu hỏi trong hệ thống.',
		'edit_a_popup' => 'Sửa câu trả lời',
		'edit_a_title' => 'Sửa câu trả lời',
		'edit_button' => 'sửa',
		'edit_c_popup' => 'Sửa bình luận này',
		'edit_c_title' => 'Sửa bình luận',
		'edit_must_confirm' => 'Hãy ^5xác thực địa chỉ email của bạn^6 để chỉnh sửa.',
		'edit_must_login' => 'Hãy ^1đăng nhập^2 hoặc ^3đăng ký^4 để chỉnh sửa.',
		'edit_q_popup' => 'Sửa câu hỏi này',
		'edit_q_title' => 'Sửa câu hỏi',
		'example_tags' => 'Ví dụ từ khóa: ',
		'flag_a_popup' => 'Câu trả lời này là rác hoặc không phù hợp',
		'flag_button' => 'vi phạm',
		'flag_c_popup' => 'Bình luận này là rác hoặc không phù hợp',
		'flag_hide_button' => 'vi phạm và ẩn',
		'flag_limit' => 'Đã có quá nhiều vi phạm - hãy thử lại trong 1 giờ',
		'flag_must_confirm' => 'Hãy ^5xác thực email của bạn^6 để báo cáo vi phạm.',
		'flag_must_login' => 'Hãy ^1đăng nhập^2 hoặc ^3đăng ký^4 để báo cáo vi phạm.',
		'flag_not_allowed' => 'Không được báo cáo vi phạm',
		'flag_q_popup' => 'Câu hỏi này là rác hoặc không phù hợp',
		'follow_a_popup' => 'Tạo câu hỏi liên quan đến câu trả lời này',
		'follow_button' => 'tạo câu hỏi liên quan',
		'follows_a' => 'liên quan đến một câu trả lời của câu hỏi:',
		'follows_q' => 'thông tin về câu hỏi:',
		'hide_a_popup' => 'Ẩn câu trả lời này',
		'hide_button' => 'ẩn',
		'hide_c_popup' => 'Ẩn bình luận này',
		'hide_q_popup' => 'Ẩn câu hỏi này',
		'matching_tags' => 'Tìm từ khóa trùng: ',
		'max_tags_x' => 'Nhiều nhất là ^ từ khóa',
		'min_tags_x' => 'Hãy chọn ít nhất là ^  từ khóa',
		'notify_email_note' => 'Bảo mật: Địa chỉ email của bạn chỉ được dùng để gửi thông báo.',
		'q_category_label' => 'Chọn chuyên mục:',
		'q_content_label' => 'Nội dung câu hỏi:',
		'q_hidden_author' => 'Câu hỏi này đã bị ẩn bởi người tạo',
		'q_hidden_flagged' => 'Câu hỏi này đã bị báo cáo vi phạm và ẩn',
		'q_hidden_other' => 'Câu hỏi này đã bị ẩn',
		'q_notify_email' => 'Gửi email cho tôi vào địa chỉ này nếu câu trả lời được chấp nhận hoặc có bình luận:',
		'q_notify_label' => 'Gửi email cho tôi nếu câu trả lời được chấp nhận hoặc có bình luận',
		'q_notify_x_label' => 'Gửi email cho tôi (^) nếu câu trả lời được chấp nhận hoặc có bình luận',
		'q_tags_comma_label' => 'Từ khóa - dùng dấu phẩy (,) để phân cách:',
		'q_tags_label' => 'Từ khóa - dùng dấu "-" để nối các từ:',
		'q_title_label' => 'Tóm tắt câu hỏi trong một dòng:',
		'q_waiting_approval' => 'Câu hỏi này đang đợi được châp nhận',
		'q_waiting_your_approval' => 'Câu hỏi này đang đợi sự chấp nhận của bạn',
		'q_your_waiting_approval' => 'Câu hỏi của bạn đã được chọn và chấp thuận ngay thôi.',
		'recat_button' => 'Chọn lại thể loại',
		'recat_popup' => 'Đổi thể loại của những câu hỏi',
		'recat_q_title' => 'Chọn lại thể loại cho câu hỏi',
		'reject_a_popup' => 'Từ chối trả lời này',
		'reject_button' => 'từ chối',
		'reject_c_popup' => 'Từ chối bình luận này',
		'reject_q_popup' => 'Từ chối câu hỏi này',
		'remove_q_favorites' => 'Gỡ bỏ câu hỏi ra khỏi yêu thích',
		'reopen_button' => 'mở lại',
		'reopen_q_popup' => 'Mở lại câu hỏi này',
		'reply_button' => 'trả lời',
		'reply_c_popup' => 'Hiện lại bình luận',
		'reshow_a_popup' => 'Hiện lại câu hỏi',
		'reshow_button' => 'hiện lại',
		'reshow_c_popup' => 'Hiện lại bình luận này',
		'reshow_q_popup' => 'Hiện lại câu hỏi này',
		'retag_button' => 'chọn lại từ khóa',
		'retag_cat_popup' => 'Đổi thể loại hoặc từ khóa của câu hỏi này',
		'retag_popup' => 'Đổi từ khóa của câu hỏi',
		'retag_q_title' => 'Chọn lại từ khóa',
		'save_silent_label' => 'Lưu câu hỏi, nhưng không cho người khác biết nó đã bị sửa',
		'select_popup' => 'Nhấn để chọn câu hỏi hay nhất',
		'select_text' => 'Hay nhất',
		'show_1_comment' => 'Hiển thị một bình luận',
		'show_1_previous_comment' => 'Hiển thị một bình luận trước',
		'show_x_comments' => 'Hiển thị ^ bình luận',
		'show_x_previous_comments' => 'Hiển thị ^ bình luận trước',
		'unflag_button' => 'bỏ vi phạm',
		'unflag_popup' => 'Bỏ vi phạm bạn đã thêm',
		'unselect_popup' => 'Nhấn chuột để bỏ chọn',
		'x_answers_title' => '^ Trả lời',
		'your_answer_title' => 'Câu trả lời của bạn',
		'your_comment_a' => 'Bình luận của bạn cho câu hỏi này:',
		'your_comment_q' => 'Bình luận của bạn về câu hỏi này:',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
