<?php
/*
	Question2Answer by Gideon Greenspan and contributors
	http://www.question2answer.org/

	File: qa-include/qa-lang-main.php
	Description: Language phrases commonly used throughout Q2A


	This program is free software; you can redistribute it and/or
	modify it under the terms of the GNU General Public License
	as published by the Free Software Foundation; either version 2
	of the License, or (at your option) any later version.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	More about this license: http://www.question2answer.org/license.php
*/

	return array(
		'1_answer' => '1 trả lời',
		'1_comment' => '1 bình luận',
		'1_day' => '1 ngày',
		'1_disliked' => '1 không thích',
		'1_flag' => '1 vi phạm',
		'1_hour' => '1 giờ',
		'1_liked' => '1 thích',
		'1_minute' => '1 phút',
		'1_month' => '1 tháng',
		'1_point' => '1 điểm',
		'1_question' => '1 câu hỏi',
		'1_second' => '1 giây',
		'1_tag' => '1 từ khóa',
		'1_user' => '1 thành viên',
		'1_view' => '1 đã xem',
		'1_vote' => '1 thích',
		'1_week' => '1 tuần',
		'1_year' => '1 năm',
		'add_category_x_favorites' => 'Thêm  ^ vào thể loại yêu thích của tôi ',
		'add_favorites' => 'Thêm vào yêu thích',
		'add_tag_x_favorites' => 'Thêm ^ vào yêu thích của tôi',
		'all_categories' => 'Tất cả chuyên mục',
		'anonymous' => 'vô danh',
		'answer_edited' => 'câu hỏi đã được sửa',
		'answer_reshown' => 'câu trả lời đã hiển thị lại',
		'answer_selected' => 'đã chọn câu trả lời',
		'answered' => 'trả lời',
		'answered_qs_in_x' => 'Câu hỏi được trả lời nhiều nhất trong ^',
		'answered_qs_title' => 'Câu hỏi được trả lời nhiều nhất',
		'asked' => 'đã hỏi',
		'asked_related_q' => 'tạo câu hỏi liên quan',
		'by_x' => 'bởi ^',
		'cancel_button' => 'Bỏ qua',
		'closed' => 'đã đóng',
		'comment_edited' => 'bình luận đã được sửa',
		'comment_moved' => 'bình luận đã được di chuyển',
		'comment_reshown' => 'đã hiện lại bình luận',
		'commented' => 'đã bình luận',
		'date_day_min_digits' => 1, // 1 or 2
	    'date_format_other_years' => 'ngày ^day ^month năm ^year',
		'date_format_this_year' => 'ngày ^day ^month',
		'date_month_1' => 'tháng 1',
		'date_month_2' => 'tháng 2',
		'date_month_3' => 'tháng 3',
		'date_month_4' => 'tháng 4',
		'date_month_5' => 'tháng 5',
		'date_month_6' => 'tháng 6',
		'date_month_7' => 'tháng 7',
		'date_month_8' => 'tháng 8',
		'date_month_9' => 'tháng 9',
		'date_month_10' => 'tháng 10',
		'date_month_11' => 'tháng 11',
		'date_month_12' => 'tháng 12',
		'date_year_digits' => 4, // 2 or 4
		'edited' => 'đã sửa',
		'email_error' => 'Đã có lỗi khi gửi email.',
		'field_required' => 'Hãy nhập dữ liệu vào trường này',
		'file_upload_limit_exceeded' => 'The size of the file exceeds the server\'s limits',
		'general_error' => 'Máy chủ gặp lỗi - hãy thử lại lần nữa.',
		'hidden' => 'ẩn',
		'highest_users' => 'Thành viên điểm cao',
		'hot_qs_in_x' => 'Câu hỏi mới trong ^',
		'hot_qs_title' => 'Câu hỏi mới',
		'image_not_read' => 'Ảnh không đúng định dạng. Hãy chọn một trong những định dạng sau: ^',
		'image_too_big_x_pc' => 'Ảnh này quá lớn. Hãy sửa bức ảnh lại ^% và thử một lần nữa.',
		'in_category_x' => 'trong ^',
		'ip_address_x' => 'địa chỉ IP  ^',
		'logged_in_x' => 'Xin chào ^',
		'max_length_x' => 'Số ký tự tối đa là ^ ký tự',
		'max_upload_size_x' => 'Dung lượng ảnh tối đa là ^',
		'me' => 'tôi',
		'meta_order' => '^what^when^where^who',  // you can reorder but DO NOT translate! e.g. <answered> <15 hours ago> <in Problems> <by me (500 points)>
		'min_length_x' => 'Hãy thêm thông tin - ít nhất là ^ ký tự',
		'moved' => 'đã chuyển',
		'nav_activity' => 'Tất cả hoạt động',
		'nav_admin' => 'Quản trị',
		'nav_ask' => 'Tạo câu hỏi',
		'nav_categories' => 'Chuyên mục',
		'nav_feedback' => 'Gửi ý kiến đóng góp',
		'nav_home' => 'Trang chủ',
		'nav_hot' => 'Mới!',
		'nav_login' => 'Đăng nhập',
		'nav_logout' => 'Thoát',
		'nav_most_answers' => 'Mới trả lời',
		'nav_most_recent' => 'Gần đây',
		'nav_most_views' => 'Xem nhiều nhất',
		'nav_most_votes' => 'Thích nhiều nhất',
		'nav_no_answer' => 'Không có câu trả lời',
		'nav_no_selected_answer' => 'Chưa chấp nhận',
		'nav_no_upvoted_answer' => 'Chưa ai thích',
		'nav_qa' => 'Q&A',
		'nav_qs' => 'Danh sách câu hỏi',
		'nav_register' => 'Đăng ký',
		'nav_tags' => 'Từ khóa',
		'nav_unanswered' => 'Chưa trả lời',
		'nav_updates' => 'Cập nhật của bạn',
		'nav_users' => 'Thành viên',
		'no_active_users' => 'không tìm thấy thành viên tích cực',
		'no_answers_found' => 'Không tìm thấy trả lời',
		'no_answers_in_x' => 'Không có trả lời trong ^',
		'no_categories_found' => 'Không tìm thấy thể loại',
		'no_category' => 'Không có thể loại',
		'no_comments_found' => 'Không tìm thấy bình luận',
		'no_comments_in_x' => 'Không có bình luận trong ^',
		'no_questions_found' => 'Không tìm thấy câu hỏi',
		'no_questions_in_x' => 'Không có câu hỏi trong ^',
		'no_related_qs_title' => 'Không tìm thấy câu hỏi liên quan',
		'no_results_for_x' => 'Không tìm thấy kết quả cho ^',
		'no_tags_found' => 'Không tìm thấy từ khóa',
		'no_una_questions_found' => 'Tất cả câu hỏi đã có câu trả lời',
		'no_una_questions_in_x' => 'Không tìm thấy câu hỏi chưa được trả lời trong ^',
		'no_unselected_qs_found' => 'Không tìm thấy câu hỏi nào chưa chọn câu trả lời',
		'no_unupvoteda_qs_found' => 'Không tìm thấy câu hỏi nào chưa được thích',
		'page_label' => 'Trang:',
		'page_next' => 'kế tiếp',
		'page_not_found' => 'Không tìm thấy trang này',
		'page_prev' => 'trước',
		'popular_tags' => 'Từ khóa phổ biến nhất',
		'questions_tagged_x' => 'Câu hỏi gần đây với từ khóa: ^',
		'recategorized' => 'chọn lại thể loại',
		'recent_activity_in_x' => 'Hoạt động gần đây trong ^',
		'recent_activity_title' => 'Hoạt động gần đây',
		'recent_as_in_x' => 'Câu trả lời gần đây trong ^',
		'recent_as_title' => 'Câu trả lời gần đây',
		'recent_cs_in_x' => 'Bình luận gần đây trong ^',
		'recent_cs_title' => 'Bình luận gần đây',
		'recent_qs_as_in_x' => 'Câu hỏi và trả lời trong ^',
		'recent_qs_as_title' => 'Câu hỏi và trả lời gần đây',
		'recent_qs_in_x' => 'Câu hỏi gần đây trong ^',
		'recent_qs_title' => 'Những câu hỏi gần đây',
		'related_qs_title' => 'Những câu hỏi liên quan',
		'remove_favorites' => 'Xóa khỏi yêu thích',
		'remove_x_favorites' => 'Xóa ^ khỏi yêu thích',
		'reopened' => 'mở lại',
		'reshown' => 'hiện lại',
		'results_for_x' => 'Kết quả tìm kiếm cho ^',
		'retagged' => 'chọn từ khóa lại',
		'save_button' => 'Lưu thay đổi',
		'search_button' => 'Tìm kiếm',
		'search_explanation' => 'Hãy nhập từ khóa tìm kiếm và thử lại.',
		'search_title' => 'Kết quả tìm kiếm',
		'selected' => 'đã được chọn',
		'send_button' => 'Gửi',
		'since_x' => 'từ ^',
		'suggest_ask' => 'Hãy bắt đầu mọi thứ ^1bằng một câu hỏi^2.',
		'suggest_category_qs' => 'Xem nhiều hơn, hãy nhấn vào tất cả câu hỏi của ^1 trong danh mục ^2.',
		'suggest_qs' => 'Xem nhiều hơn, hãy nhấn vào ^1danh sách tất cả câu hỏi^2.',
		'suggest_qs_tags' => 'Xem nhiều hơn, hãy nhấn vào ^1 danh sách câu hỏi ^2 hoặc ^3 danh sách từ khóa ^4.',
		'to_x' => 'đến ^',
		'unanswered_qs_in_x' => 'Câu hỏi chưa có câu trả lời trong ^',
		'unanswered_qs_title' => 'Những câu hỏi chưa có câu trả lời',
		'unselected_qs_in_x' => 'Câu hỏi chưa chọn một câu trả lời trong ^',
		'unselected_qs_title' => 'Những câu hỏi có câu trả lời nhưng chưa được chấp nhận',
		'unupvoteda_qs_in_x' => 'Câu hỏi có câu trả lời chưa được thích ^',
		'unupvoteda_qs_title' => 'Câu hỏi gần đây có câu trả lời chưa được thích',
		'upload_limit' => 'Quá nhiều dữ liệu được tải lên - hãy thử lại trong một giờ',
		'view_q_must_be_approved' => 'Tài khoản của bạn cần được xác nhận trước khi xem câu hỏi.',
		'view_q_must_confirm' => 'Hãy ^5xác nhận địa chỉ email của bạn^6 để xem câu hỏi.',
		'view_q_must_login' => 'Hãy ^1đăng nhập^2 hoặc ^3đăng ký^4 để xem câu hỏi.',
		'viewed_qs_in_x' => 'Câu hỏi được xem nhiều nhất trong ^',
		'viewed_qs_title' => 'Câu hỏi được xem nhiều nhất',
		'vote_disabled_approve' => 'Tài khoản của bạn cần được xác nhận trước khi thích',
		'vote_disabled_down' => 'Chỉ một số thành viên được chọn không thích',
		'vote_disabled_down_approve' => 'Tài khoản của bạn phải được xác nhận trước khi bạn chọn không thích',
		'vote_disabled_hidden_a' => 'Bạn không thể thích câu trả lời đã bị ẩn',
		'vote_disabled_hidden_q' => 'Bạn không thể thích câu hỏi đã bị ẩn',
		'vote_disabled_level' => 'Chỉ một số thành viên được đánh giá câu hỏi',
		'vote_disabled_my_a' => 'Bạn không thể tự thích câu trả lời của bạn',
		'vote_disabled_my_q' => 'Bạn không thể tự thích câu hỏi của bạn',
		'vote_disabled_q_page_only' => 'Hãy xem qua câu hỏi để thích',
		'vote_down_must_confirm' => 'Hãy ^5xác nhận địa chỉ email của bạn^6 để chọn không thích.',
		'vote_down_popup' => 'Nhấn để không thích',
		'vote_limit' => 'Máy chủ nhận được quá nhiều ý kiến lúc này - hãy thử lại trong một giờ',
		'vote_must_confirm' => 'Hãy ^5xác nhận địa chỉ email^6 để thích.',
		'vote_must_login' => 'Hãy  ^1đăng nhập^2 hoặc ^3đăng ký^4 để thích.',
		'vote_not_allowed' => 'Không được cho ý kiến ở mục này',
		'vote_up_popup' => 'Nhấn để thích',
		'voted_down_popup' => 'Bạn đã không thích câu hỏi này - nhấn để bỏ không thích',
		'voted_qs_in_x' => 'Câu hỏi được yêu thích nhất trong ^',
		'voted_qs_title' => 'Câu hỏi được yêu thích nhất',
		'voted_up_popup' => 'Bạn đã thích câu hỏi này - nhấn để bỏ thích',
		'written' => '', // blank in English - placeholder for other languages
		'x_ago' => '^ trước',
		'x_answers' => '^ trả lời',
		'x_comments' => '^ bình luận',
		'x_days' => '^ ngày',
		'x_disliked' => '^ k thích',
		'x_flags' => '^ vi phạm',
		'x_hours' => '^ giờ',
		'x_liked' => '^ thích',
		'x_minutes' => '^ phút',
		'x_months' => '^ tháng',
		'x_points' => '^ điểm',
		'x_questions' => '^ câu hỏi',
		'x_seconds' => '^ giây',
		'x_tags' => '^ từ khóa',
		'x_users' => '^ thành viên',
		'x_views' => '^ đã xem',
		'x_votes' => '^ k thích',
		'x_weeks' => '^ tuần',
		'x_years' => '^ năm',
	);


/*
	Omit PHP closing tag to help avoid accidental output
*/
